#!/bin/sh
set -e
/home/scottflo/fivm/bin/fivmc -o lib/targets/POSIX-linux-gnu-i686-32/cmacros.conf --target POSIX-linux-gnu-i686-32 --process-cmacros -A cha --code-repo disk --sanity-check 1 -v 1 --no-regen --no-scripts "$@"
