/*
 * GenSettings.java
 * Copyright 2008, 2009, 2010, 2011, 2012, 2013 Fiji Systems Inc.
 * This file is part of the FIJI VM Software licensed under the FIJI PUBLIC
 * LICENSE Version 3 or any later version.  A copy of the FIJI PUBLIC LICENSE is
 * available at fivm/LEGAL and can also be found at
 * http://www.fiji-systems.com/FPL3.txt
 * 
 * By installing, reproducing, distributing, and/or using the FIJI VM Software
 * you agree to the terms of the FIJI PUBLIC LICENSE.  You may exercise the
 * rights granted under the FIJI PUBLIC LICENSE subject to the conditions and
 * restrictions stated therein.  Among other conditions and restrictions, the
 * FIJI PUBLIC LICENSE states that:
 * 
 * a. You may only make non-commercial use of the FIJI VM Software.
 * 
 * b. Any adaptation you make must be licensed under the same terms 
 * of the FIJI PUBLIC LICENSE.
 * 
 * c. You must include a copy of the FIJI PUBLIC LICENSE in every copy of any
 * file, adaptation or output code that you distribute and cause the output code
 * to provide a notice of the FIJI PUBLIC LICENSE. 
 * 
 * d. You must not impose any additional conditions.
 * 
 * e. You must not assert or imply any connection, sponsorship or endorsement by
 * the author of the FIJI VM Software
 * 
 * f. You must take no derogatory action in relation to the FIJI VM Software
 * which would be prejudicial to the FIJI VM Software author's honor or
 * reputation.
 * 
 * 
 * The FIJI VM Software is provided as-is.  FIJI SYSTEMS INC does not make any
 * representation and provides no warranty of any kind concerning the software.
 * 
 * The FIJI PUBLIC LICENSE and any rights granted therein terminate
 * automatically upon any breach by you of the terms of the FIJI PUBLIC LICENSE.
 */

package com.fiji.fivm.util;

import com.fiji.fivm.*;
import com.fiji.fivm.c1.*;
import java.io.*;
import java.lang.reflect.*;

public class GenSettings {
    public static void main(String[] v) throws Throwable {
        PrintWriter w;
        w=Util.wrap(new SmartUpdateFileOutputStream(
                        "runtimec/src/fivmr_settings_fields.h"));
        w.println("/* generated by GenSettings */");
        w.println("/* DO NOT EDIT! */");
        int cnt=0;
        for (Field f : Settings.class.getFields()) {
            if (!f.isSynthetic() && !f.isAnnotationPresent(SysDepSetting.class)) {
                cnt++;
            }
        }
        w.println("uint32_t flags["+((cnt+31)/32)+"];");
        w.close();
        
        w=Util.wrap(new SmartUpdateFileOutputStream(
                        "runtimec/src/fivmr_settings_getters.h"));
        w.println("/* generated by GenSettings */");
        w.println("/* DO NOT EDIT! */");
        cnt=0;
        for (Field f : Settings.class.getFields()) {
            if (!f.isSynthetic() && !f.isAnnotationPresent(SysDepSetting.class)) {
                w.println("#ifdef FIVMBUILD_FORCE__"+f.getName());
                w.println("#define FIVMR_"+f.getName()+"(settings) (FIVMBUILD__"+f.getName()+")");
                w.println("#else");
                w.println("#define FIVMR_"+f.getName()+"(settings) (!!((settings)->flags["+(cnt/32)+"]&UINT32_C("+(1l<<(cnt%32))+")))");
                w.println("#endif");
                cnt++;
            }
        }
        w.close();
    }
}

