#!/bin/sh
set -e
/home/scottflo/repos/cse605/fivm/bin/fivmc --target local-32 -o lib/hf-pip-ctypes.tmp --extract-ctypes --ct-compute-offsets --ct-incl-generated no -A cha -G hf --lock-mode pip -v 1 --no-regen --no-scripts "$@"
