/* generated by fivmc */
/* DO NOT EDIT!! */
#define FIVMC_SYS_NAME "POSIX-linux-gnu-i686-32"
#define FIVMC_CMD "/home/scottflo/fivm/bin/fivmc -o hello src/build/test/HelloArray.class src/build/test/Kaymar.class --no-opt"
#define FIVMC_DIR "/home/scottflo/scratch"
#define FIVMC_HOSTINFO "Linux ubuntu 3.16.0-30-generic #40~14.04.1-Ubuntu SMP Thu Jan 15 17:45:15 UTC 2015 i686 i686 i686 GNU/Linux"
#define FIVMC_DATE "2015-04-10 11:34:30 -0400"
#define FIVMC_HOMEDIR "/home/scottflo/fivm"
#define FIVMC_OUTPUT hello
