/* generated by fivmc */
/* DO NOT EDIT!! */
#define FIVMC_SYS_NAME "POSIX-linux-gnu-x86_64-64"
#define FIVMC_CMD "/home/scottflo/repos/cse605/fivm/bin/fivmc --target local-64 -o lib/cmr-biased-ctypes.tmp --extract-ctypes --ct-compute-offsets --ct-incl-generated no -A cha -G cmr --lock-mode biased"
#define FIVMC_DIR "/home/scottflo/repos/cse605/fivm"
#define FIVMC_HOSTINFO "Linux sflub 3.13.0-45-generic #74-Ubuntu SMP Tue Jan 13 19:36:28 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux"
#define FIVMC_DATE "2015-04-15 22:04:19 -0400"
#define FIVMC_HOMEDIR "/home/scottflo/repos/cse605/fivm"
#define FIVMC_OUTPUT cmr_002dbiased_002dctypes_002etmp
