/* generated by fivmc */
/* DO NOT EDIT!! */
#define FIVMC_SYS_NAME "POSIX-linux-gnu-i686-32"
#define FIVMC_CMD "/home/scottflo/repos/cse605/fivm/bin/fivmc --target local-32 -o lib/cmr-biased-ctypes.tmp --extract-ctypes --ct-compute-offsets --ct-incl-generated no -A open -G cmr --lock-mode biased"
#define FIVMC_DIR "/home/scottflo/repos/cse605/fivm"
#define FIVMC_HOSTINFO "Linux ubuntu 3.16.0-30-generic #40~14.04.1-Ubuntu SMP Thu Jan 15 17:45:15 UTC 2015 i686 i686 i686 GNU/Linux"
#define FIVMC_DATE "2015-04-15 10:15:00 -0400"
#define FIVMC_HOMEDIR "/home/scottflo/repos/cse605/fivm"
#define FIVMC_OUTPUT cmr_002dbiased_002dctypes_002etmp
