#!/bin/sh
set -e
/home/scottflo/repos/cse605/fivm/bin/fivmc --target local-64 -o lib/cmr-biased-ctypes.tmp --extract-ctypes --ct-compute-offsets --ct-incl-generated no -A cha -G cmr --lock-mode biased -v 1 --no-regen --no-scripts "$@"
