#define FIVMSYS_ARCH "x86_64"
#define FIVMSYS_OS "linux-gnu"

#define FIVMR_PROFILE_MONITOR 0
#define FIVMR_PROFILE_MONITOR_HEAVY 0
#define FIVMR_PROFILE_GC 0
#define FIVMR_PROFILE_GC_HEAVY 0
#define FIVMR_PROFILE_REFLECTION 0
#define FIVMR_COVERAGE 0
#define FIVMR_POSIX_IO 1
#define FIVMR_WIN32 0
#define FIVMR_STATIC_JNI 0
#define FIVMR_PF_POLLCHECK 0
#define FIVMR_INTERNAL_INST 0
#define FIVMR_PARALLEL_C1 1
#define FIVMR_LOG_CODE_REPO_ACCESSES 0
#define FIVMR_SPC_ENABLED 0
#define FIVMR_STACK_GROWS_DOWN 1 /* FIXME */

#define FIVMR_POSIX 1
#ifdef FIVMR_POSIX
#define FIVMR_RTEMS 0
#define FIVMR_DYN_LOADING 1
#define FIVMR_UNIPROCESSOR 0
#define FIVMR_SUPPORT_SIGQUIT 1
#else
#define FIVMR_POSIX 0
#define FIVMR_DYN_LOADING 0
#define FIVMR_UNIPROCESSOR 1
#define FIVMR_SUPPORT_SIGQUIT 0
#endif

#define FIVMR_IS_LITTLE_ENDIAN 1
#ifdef FIVMR_IS_BIG_ENDIAN
#define FIVMR_IS_LITTLE_ENDIAN 0
#else
#define FIVMR_IS_BIG_ENDIAN 0
#endif

#define FIVMR_NEED_ALL_HELPERS 1

#define FIVMR_SYNC_GCC_INTRINSIC 1

#include "fivmc_tag_dep_config.h"

#ifndef FIVMSYS_PTRSIZE
#define FIVMSYS_PTRSIZE 4
#endif
#ifndef FIVMSYS_LOG_PAGE_SIZE
#define FIVMSYS_LOG_PAGE_SIZE 12
#endif

#define FIVMR_BACKEND_X86 1
#ifdef FIVMR_BACKEND_
#undef FIVMR_BACKEND_
#endif
#ifdef FIVMR_BACKEND_X86
#define FIVMR_X86 1
#if FIVMSYS_PTRSIZE!=4
#error "Invalid configuration: cannot have X86 with pointer size not 4"
#endif
#undef FIVMR_BACKEND_X86
#endif

#ifndef FIVMR_X86
#define FIVMR_X86 0
#endif

#define FIVMR_CAN_DO_CLASSLOADING (FIVMR_X86)

#define FIVMR_LOG_GC_MARK_TRAPS 0

