/* generated by GenSettings */
/* DO NOT EDIT! */
#ifdef FIVMBUILD_FORCE__PROFILE_STACK_HEIGHT
#define FIVMR_PROFILE_STACK_HEIGHT(settings) (FIVMBUILD__PROFILE_STACK_HEIGHT)
#else
#define FIVMR_PROFILE_STACK_HEIGHT(settings) (!!((settings)->flags[0]&UINT32_C(1)))
#endif
#ifdef FIVMBUILD_FORCE__CLASSLOADING
#define FIVMR_CLASSLOADING(settings) (FIVMBUILD__CLASSLOADING)
#else
#define FIVMR_CLASSLOADING(settings) (!!((settings)->flags[0]&UINT32_C(2)))
#endif
#ifdef FIVMBUILD_FORCE__HM_NARROW
#define FIVMR_HM_NARROW(settings) (FIVMBUILD__HM_NARROW)
#else
#define FIVMR_HM_NARROW(settings) (!!((settings)->flags[0]&UINT32_C(4)))
#endif
#ifdef FIVMBUILD_FORCE__HM_POISONED
#define FIVMR_HM_POISONED(settings) (FIVMBUILD__HM_POISONED)
#else
#define FIVMR_HM_POISONED(settings) (!!((settings)->flags[0]&UINT32_C(8)))
#endif
#ifdef FIVMBUILD_FORCE__OM_CONTIGUOUS
#define FIVMR_OM_CONTIGUOUS(settings) (FIVMBUILD__OM_CONTIGUOUS)
#else
#define FIVMR_OM_CONTIGUOUS(settings) (!!((settings)->flags[0]&UINT32_C(16)))
#endif
#ifdef FIVMBUILD_FORCE__OM_FRAGMENTED
#define FIVMR_OM_FRAGMENTED(settings) (FIVMBUILD__OM_FRAGMENTED)
#else
#define FIVMR_OM_FRAGMENTED(settings) (!!((settings)->flags[0]&UINT32_C(32)))
#endif
#ifdef FIVMBUILD_FORCE__FORCE_ARRAYLETS
#define FIVMR_FORCE_ARRAYLETS(settings) (FIVMBUILD__FORCE_ARRAYLETS)
#else
#define FIVMR_FORCE_ARRAYLETS(settings) (!!((settings)->flags[0]&UINT32_C(64)))
#endif
#ifdef FIVMBUILD_FORCE__MAIN_IN_THREAD
#define FIVMR_MAIN_IN_THREAD(settings) (FIVMBUILD__MAIN_IN_THREAD)
#else
#define FIVMR_MAIN_IN_THREAD(settings) (!!((settings)->flags[0]&UINT32_C(128)))
#endif
#ifdef FIVMBUILD_FORCE__VERBOSE_RUN_METHOD
#define FIVMR_VERBOSE_RUN_METHOD(settings) (FIVMBUILD__VERBOSE_RUN_METHOD)
#else
#define FIVMR_VERBOSE_RUN_METHOD(settings) (!!((settings)->flags[0]&UINT32_C(256)))
#endif
#ifdef FIVMBUILD_FORCE__DUMB_HASH_CODE
#define FIVMR_DUMB_HASH_CODE(settings) (FIVMBUILD__DUMB_HASH_CODE)
#else
#define FIVMR_DUMB_HASH_CODE(settings) (!!((settings)->flags[0]&UINT32_C(512)))
#endif
#ifdef FIVMBUILD_FORCE__BIASED_LOCKING
#define FIVMR_BIASED_LOCKING(settings) (FIVMBUILD__BIASED_LOCKING)
#else
#define FIVMR_BIASED_LOCKING(settings) (!!((settings)->flags[0]&UINT32_C(1024)))
#endif
#ifdef FIVMBUILD_FORCE__PIP_LOCKING
#define FIVMR_PIP_LOCKING(settings) (FIVMBUILD__PIP_LOCKING)
#else
#define FIVMR_PIP_LOCKING(settings) (!!((settings)->flags[0]&UINT32_C(2048)))
#endif
#ifdef FIVMBUILD_FORCE__NOGC
#define FIVMR_NOGC(settings) (FIVMBUILD__NOGC)
#else
#define FIVMR_NOGC(settings) (!!((settings)->flags[0]&UINT32_C(4096)))
#endif
#ifdef FIVMBUILD_FORCE__CMRGC
#define FIVMR_CMRGC(settings) (FIVMBUILD__CMRGC)
#else
#define FIVMR_CMRGC(settings) (!!((settings)->flags[0]&UINT32_C(8192)))
#endif
#ifdef FIVMBUILD_FORCE__HFGC
#define FIVMR_HFGC(settings) (FIVMBUILD__HFGC)
#else
#define FIVMR_HFGC(settings) (!!((settings)->flags[0]&UINT32_C(16384)))
#endif
#ifdef FIVMBUILD_FORCE__SELF_MANAGE_MEM
#define FIVMR_SELF_MANAGE_MEM(settings) (FIVMBUILD__SELF_MANAGE_MEM)
#else
#define FIVMR_SELF_MANAGE_MEM(settings) (!!((settings)->flags[0]&UINT32_C(32768)))
#endif
#ifdef FIVMBUILD_FORCE__PREDICTABLE_OOME
#define FIVMR_PREDICTABLE_OOME(settings) (FIVMBUILD__PREDICTABLE_OOME)
#else
#define FIVMR_PREDICTABLE_OOME(settings) (!!((settings)->flags[0]&UINT32_C(65536)))
#endif
#ifdef FIVMBUILD_FORCE__GC_BLACK_STACK
#define FIVMR_GC_BLACK_STACK(settings) (FIVMBUILD__GC_BLACK_STACK)
#else
#define FIVMR_GC_BLACK_STACK(settings) (!!((settings)->flags[0]&UINT32_C(131072)))
#endif
#ifdef FIVMBUILD_FORCE__GLIBJ
#define FIVMR_GLIBJ(settings) (FIVMBUILD__GLIBJ)
#else
#define FIVMR_GLIBJ(settings) (!!((settings)->flags[0]&UINT32_C(262144)))
#endif
#ifdef FIVMBUILD_FORCE__FIJICORE
#define FIVMR_FIJICORE(settings) (FIVMBUILD__FIJICORE)
#else
#define FIVMR_FIJICORE(settings) (!!((settings)->flags[0]&UINT32_C(524288)))
#endif
#ifdef FIVMBUILD_FORCE__INCLUDE_PROFILER
#define FIVMR_INCLUDE_PROFILER(settings) (FIVMBUILD__INCLUDE_PROFILER)
#else
#define FIVMR_INCLUDE_PROFILER(settings) (!!((settings)->flags[0]&UINT32_C(1048576)))
#endif
#ifdef FIVMBUILD_FORCE__GC_DEBUG
#define FIVMR_GC_DEBUG(settings) (FIVMBUILD__GC_DEBUG)
#else
#define FIVMR_GC_DEBUG(settings) (!!((settings)->flags[0]&UINT32_C(2097152)))
#endif
#ifdef FIVMBUILD_FORCE__HFGC_PREDICT_NO_ARRAYLETS
#define FIVMR_HFGC_PREDICT_NO_ARRAYLETS(settings) (FIVMBUILD__HFGC_PREDICT_NO_ARRAYLETS)
#else
#define FIVMR_HFGC_PREDICT_NO_ARRAYLETS(settings) (!!((settings)->flags[0]&UINT32_C(4194304)))
#endif
#ifdef FIVMBUILD_FORCE__HFGC_PREDICT_ARRAYLETS
#define FIVMR_HFGC_PREDICT_ARRAYLETS(settings) (FIVMBUILD__HFGC_PREDICT_ARRAYLETS)
#else
#define FIVMR_HFGC_PREDICT_ARRAYLETS(settings) (!!((settings)->flags[0]&UINT32_C(8388608)))
#endif
#ifdef FIVMBUILD_FORCE__HFGC_TRY_CONTIGUOUS_ARRAYS
#define FIVMR_HFGC_TRY_CONTIGUOUS_ARRAYS(settings) (FIVMBUILD__HFGC_TRY_CONTIGUOUS_ARRAYS)
#else
#define FIVMR_HFGC_TRY_CONTIGUOUS_ARRAYS(settings) (!!((settings)->flags[0]&UINT32_C(16777216)))
#endif
#ifdef FIVMBUILD_FORCE__HFGC_ALL_ARRAYLETS
#define FIVMR_HFGC_ALL_ARRAYLETS(settings) (FIVMBUILD__HFGC_ALL_ARRAYLETS)
#else
#define FIVMR_HFGC_ALL_ARRAYLETS(settings) (!!((settings)->flags[0]&UINT32_C(33554432)))
#endif
#ifdef FIVMBUILD_FORCE__HFGC_FAIL_FAST_PATHS
#define FIVMR_HFGC_FAIL_FAST_PATHS(settings) (FIVMBUILD__HFGC_FAIL_FAST_PATHS)
#else
#define FIVMR_HFGC_FAIL_FAST_PATHS(settings) (!!((settings)->flags[0]&UINT32_C(67108864)))
#endif
#ifdef FIVMBUILD_FORCE__INTERCEPT_ALL_OBJ_ACCESSES
#define FIVMR_INTERCEPT_ALL_OBJ_ACCESSES(settings) (FIVMBUILD__INTERCEPT_ALL_OBJ_ACCESSES)
#else
#define FIVMR_INTERCEPT_ALL_OBJ_ACCESSES(settings) (!!((settings)->flags[0]&UINT32_C(134217728)))
#endif
#ifdef FIVMBUILD_FORCE__SCOPED_MEMORY
#define FIVMR_SCOPED_MEMORY(settings) (FIVMBUILD__SCOPED_MEMORY)
#else
#define FIVMR_SCOPED_MEMORY(settings) (!!((settings)->flags[0]&UINT32_C(268435456)))
#endif
#ifdef FIVMBUILD_FORCE__USE_TYPE_EPOCHS
#define FIVMR_USE_TYPE_EPOCHS(settings) (FIVMBUILD__USE_TYPE_EPOCHS)
#else
#define FIVMR_USE_TYPE_EPOCHS(settings) (!!((settings)->flags[0]&UINT32_C(536870912)))
#endif
#ifdef FIVMBUILD_FORCE__ITABLE_COMPRESSION
#define FIVMR_ITABLE_COMPRESSION(settings) (FIVMBUILD__ITABLE_COMPRESSION)
#else
#define FIVMR_ITABLE_COMPRESSION(settings) (!!((settings)->flags[0]&UINT32_C(1073741824)))
#endif
#ifdef FIVMBUILD_FORCE__TRACK_DIRECT_SUBS
#define FIVMR_TRACK_DIRECT_SUBS(settings) (FIVMBUILD__TRACK_DIRECT_SUBS)
#else
#define FIVMR_TRACK_DIRECT_SUBS(settings) (!!((settings)->flags[0]&UINT32_C(2147483648)))
#endif
#ifdef FIVMBUILD_FORCE__CLOSED_PATCH_POINTS
#define FIVMR_CLOSED_PATCH_POINTS(settings) (FIVMBUILD__CLOSED_PATCH_POINTS)
#else
#define FIVMR_CLOSED_PATCH_POINTS(settings) (!!((settings)->flags[1]&UINT32_C(1)))
#endif
#ifdef FIVMBUILD_FORCE__OPEN_PATCH_POINTS
#define FIVMR_OPEN_PATCH_POINTS(settings) (FIVMBUILD__OPEN_PATCH_POINTS)
#else
#define FIVMR_OPEN_PATCH_POINTS(settings) (!!((settings)->flags[1]&UINT32_C(2)))
#endif
#ifdef FIVMBUILD_FORCE__OPEN_WORLD
#define FIVMR_OPEN_WORLD(settings) (FIVMBUILD__OPEN_WORLD)
#else
#define FIVMR_OPEN_WORLD(settings) (!!((settings)->flags[1]&UINT32_C(4)))
#endif
#ifdef FIVMBUILD_FORCE__FULL_STACK_ANALYSIS
#define FIVMR_FULL_STACK_ANALYSIS(settings) (FIVMBUILD__FULL_STACK_ANALYSIS)
#else
#define FIVMR_FULL_STACK_ANALYSIS(settings) (!!((settings)->flags[1]&UINT32_C(8)))
#endif
#ifdef FIVMBUILD_FORCE__OPEN_STACK_ANALYSIS
#define FIVMR_OPEN_STACK_ANALYSIS(settings) (FIVMBUILD__OPEN_STACK_ANALYSIS)
#else
#define FIVMR_OPEN_STACK_ANALYSIS(settings) (!!((settings)->flags[1]&UINT32_C(16)))
#endif
#ifdef FIVMBUILD_FORCE__SCJ_STACK_ANALYSIS
#define FIVMR_SCJ_STACK_ANALYSIS(settings) (FIVMBUILD__SCJ_STACK_ANALYSIS)
#else
#define FIVMR_SCJ_STACK_ANALYSIS(settings) (!!((settings)->flags[1]&UINT32_C(32)))
#endif
#ifdef FIVMBUILD_FORCE__TRUSTED_STACK_ANALYSIS
#define FIVMR_TRUSTED_STACK_ANALYSIS(settings) (FIVMBUILD__TRUSTED_STACK_ANALYSIS)
#else
#define FIVMR_TRUSTED_STACK_ANALYSIS(settings) (!!((settings)->flags[1]&UINT32_C(64)))
#endif
#ifdef FIVMBUILD_FORCE__SIMPLE_COMP
#define FIVMR_SIMPLE_COMP(settings) (FIVMBUILD__SIMPLE_COMP)
#else
#define FIVMR_SIMPLE_COMP(settings) (!!((settings)->flags[1]&UINT32_C(128)))
#endif
#ifdef FIVMBUILD_FORCE__EXCEPTIONS_MAY_BE_NULL
#define FIVMR_EXCEPTIONS_MAY_BE_NULL(settings) (FIVMBUILD__EXCEPTIONS_MAY_BE_NULL)
#else
#define FIVMR_EXCEPTIONS_MAY_BE_NULL(settings) (!!((settings)->flags[1]&UINT32_C(256)))
#endif
#ifdef FIVMBUILD_FORCE__DEF_LOG_GC
#define FIVMR_DEF_LOG_GC(settings) (FIVMBUILD__DEF_LOG_GC)
#else
#define FIVMR_DEF_LOG_GC(settings) (!!((settings)->flags[1]&UINT32_C(512)))
#endif
#ifdef FIVMBUILD_FORCE__DEF_LOG_SYNC_GC
#define FIVMR_DEF_LOG_SYNC_GC(settings) (FIVMBUILD__DEF_LOG_SYNC_GC)
#else
#define FIVMR_DEF_LOG_SYNC_GC(settings) (!!((settings)->flags[1]&UINT32_C(1024)))
#endif
#ifdef FIVMBUILD_FORCE__FLOW_LOGGING_NO_SMALL_INLINES
#define FIVMR_FLOW_LOGGING_NO_SMALL_INLINES(settings) (FIVMBUILD__FLOW_LOGGING_NO_SMALL_INLINES)
#else
#define FIVMR_FLOW_LOGGING_NO_SMALL_INLINES(settings) (!!((settings)->flags[1]&UINT32_C(2048)))
#endif
#ifdef FIVMBUILD_FORCE__SCJ
#define FIVMR_SCJ(settings) (FIVMBUILD__SCJ)
#else
#define FIVMR_SCJ(settings) (!!((settings)->flags[1]&UINT32_C(4096)))
#endif
#ifdef FIVMBUILD_FORCE__RTSJ
#define FIVMR_RTSJ(settings) (FIVMBUILD__RTSJ)
#else
#define FIVMR_RTSJ(settings) (!!((settings)->flags[1]&UINT32_C(8192)))
#endif
#ifdef FIVMBUILD_FORCE__SCJ_SCOPES
#define FIVMR_SCJ_SCOPES(settings) (FIVMBUILD__SCJ_SCOPES)
#else
#define FIVMR_SCJ_SCOPES(settings) (!!((settings)->flags[1]&UINT32_C(16384)))
#endif
#ifdef FIVMBUILD_FORCE__RTSJ_SCOPES
#define FIVMR_RTSJ_SCOPES(settings) (FIVMBUILD__RTSJ_SCOPES)
#else
#define FIVMR_RTSJ_SCOPES(settings) (!!((settings)->flags[1]&UINT32_C(32768)))
#endif
#ifdef FIVMBUILD_FORCE__HAVE_SCOPE_CHECKS
#define FIVMR_HAVE_SCOPE_CHECKS(settings) (FIVMBUILD__HAVE_SCOPE_CHECKS)
#else
#define FIVMR_HAVE_SCOPE_CHECKS(settings) (!!((settings)->flags[1]&UINT32_C(65536)))
#endif
#ifdef FIVMBUILD_FORCE__HAVE_SHARED_SCOPES
#define FIVMR_HAVE_SHARED_SCOPES(settings) (FIVMBUILD__HAVE_SHARED_SCOPES)
#else
#define FIVMR_HAVE_SHARED_SCOPES(settings) (!!((settings)->flags[1]&UINT32_C(131072)))
#endif
#ifdef FIVMBUILD_FORCE__SEARCH_ROOT_CLASSES_AT_RUNTIME
#define FIVMR_SEARCH_ROOT_CLASSES_AT_RUNTIME(settings) (FIVMBUILD__SEARCH_ROOT_CLASSES_AT_RUNTIME)
#else
#define FIVMR_SEARCH_ROOT_CLASSES_AT_RUNTIME(settings) (!!((settings)->flags[1]&UINT32_C(262144)))
#endif
#ifdef FIVMBUILD_FORCE__ROOT_OVERRIDES_ALL_APP
#define FIVMR_ROOT_OVERRIDES_ALL_APP(settings) (FIVMBUILD__ROOT_OVERRIDES_ALL_APP)
#else
#define FIVMR_ROOT_OVERRIDES_ALL_APP(settings) (!!((settings)->flags[1]&UINT32_C(524288)))
#endif
#ifdef FIVMBUILD_FORCE__FULL_CHECK_INIT_SEMANTICS
#define FIVMR_FULL_CHECK_INIT_SEMANTICS(settings) (FIVMBUILD__FULL_CHECK_INIT_SEMANTICS)
#else
#define FIVMR_FULL_CHECK_INIT_SEMANTICS(settings) (!!((settings)->flags[1]&UINT32_C(1048576)))
#endif
#ifdef FIVMBUILD_FORCE__FINALIZATION_SUPPORTED
#define FIVMR_FINALIZATION_SUPPORTED(settings) (FIVMBUILD__FINALIZATION_SUPPORTED)
#else
#define FIVMR_FINALIZATION_SUPPORTED(settings) (!!((settings)->flags[1]&UINT32_C(2097152)))
#endif
#ifdef FIVMBUILD_FORCE__OPT_CM_STORE_BARRIERS
#define FIVMR_OPT_CM_STORE_BARRIERS(settings) (FIVMBUILD__OPT_CM_STORE_BARRIERS)
#else
#define FIVMR_OPT_CM_STORE_BARRIERS(settings) (!!((settings)->flags[1]&UINT32_C(4194304)))
#endif
#ifdef FIVMBUILD_FORCE__CHECK_OPT_CM_STORE_BARRIERS
#define FIVMR_CHECK_OPT_CM_STORE_BARRIERS(settings) (FIVMBUILD__CHECK_OPT_CM_STORE_BARRIERS)
#else
#define FIVMR_CHECK_OPT_CM_STORE_BARRIERS(settings) (!!((settings)->flags[1]&UINT32_C(8388608)))
#endif
#ifdef FIVMBUILD_FORCE__AGGRESSIVE_OPT_CM_STORE_BARRIERS
#define FIVMR_AGGRESSIVE_OPT_CM_STORE_BARRIERS(settings) (FIVMBUILD__AGGRESSIVE_OPT_CM_STORE_BARRIERS)
#else
#define FIVMR_AGGRESSIVE_OPT_CM_STORE_BARRIERS(settings) (!!((settings)->flags[1]&UINT32_C(16777216)))
#endif
#ifdef FIVMBUILD_FORCE__FILTERED_CM_STORE_BARRIERS
#define FIVMR_FILTERED_CM_STORE_BARRIERS(settings) (FIVMBUILD__FILTERED_CM_STORE_BARRIERS)
#else
#define FIVMR_FILTERED_CM_STORE_BARRIERS(settings) (!!((settings)->flags[1]&UINT32_C(33554432)))
#endif
#ifdef FIVMBUILD_FORCE__SUPPORT_ENV_BASED_SYS_PROPS
#define FIVMR_SUPPORT_ENV_BASED_SYS_PROPS(settings) (FIVMBUILD__SUPPORT_ENV_BASED_SYS_PROPS)
#else
#define FIVMR_SUPPORT_ENV_BASED_SYS_PROPS(settings) (!!((settings)->flags[1]&UINT32_C(67108864)))
#endif
#ifdef FIVMBUILD_FORCE__AOT_NATIVE_BACKEND
#define FIVMR_AOT_NATIVE_BACKEND(settings) (FIVMBUILD__AOT_NATIVE_BACKEND)
#else
#define FIVMR_AOT_NATIVE_BACKEND(settings) (!!((settings)->flags[1]&UINT32_C(134217728)))
#endif
#ifdef FIVMBUILD_FORCE__OMIT_FRAME_POINTER
#define FIVMR_OMIT_FRAME_POINTER(settings) (FIVMBUILD__OMIT_FRAME_POINTER)
#else
#define FIVMR_OMIT_FRAME_POINTER(settings) (!!((settings)->flags[1]&UINT32_C(268435456)))
#endif
