#!/usr/bin/env ruby

flnm1=ARGV.shift
flnm2=ARGV.shift

file1=File.open(flnm1)
file2=File.open(flnm2)

cnt=1
loop {
  line1=file1.readline
  line2=file2.readline
  if not line1
    if line2
      puts "#{flnm1} is shorter than #{flnm2} at line #{cnt}"
      exit 1
    else
      puts "files are identical"
      exit 0
    end
  end
  if not line2
    puts "#{flnm1} is longer than #{flnm2} at line #{cnt}"
    exit 1
  end
  if line1!=line2
    puts "Files differ at line #{cnt}:"
    puts "#{flnm1}: #{line1}"
    puts "#{flnm2}: #{line2}"
    exit 1
  end
  cnt+=1
}

