#!/bin/sh

set -e

localbindir=`dirname $0`

$localbindir/runspec $localbindir/../bin/fijivm-cmr-debug SpecApplication
$localbindir/runspec-gctorture $localbindir/../bin/fijivm-cmr-debug SpecApplication

