#!/bin/sh

set -e

localbindir=`dirname $0`

echo "Compiling -G cmr --type-epochs yes configuration..."
time $localbindir/../bin/fivmc --sanity-check 1 -o SPECjvm98-cmrgc-typeepoch . -m SpecApplication -G cmr --type-epochs yes

$localbindir/runspec ./SPECjvm98-cmrgc-typeepoch
$localbindir/runspec-gctorture ./SPECjvm98-cmrgc-typeepoch

